

boe:
  DB:
    host: localhost
    password: boe
    port: 3306
    user: root
    database: boe


online:
  DB:
    host: localhost
    password: boe
    port: 3306
    user: root
    database: boe