online:
  DB:
    host: 101.200.146.122
    password: YsmFmXziiaGNKr5i
    port: 3306
    user: test_plant
    database: test_plant
  redis:
    host: 101.200.146.122
    port: 6379
    db: 1
    password: testljx
  node: product
  port: 5001
